### ISSUE TITLE
Invalid Conversion

### ISSUE THREAD

**Issue by Dan-Rdd** [egefeyzioglu/Long-Range-RFID-Sniffer#1]
seem to get the following error when compiling via Arduino IDE
invalid conversion from 'const __FlashStringHelper*' to 'byte {aka unsigned char}' [-fpermissive]

**Comment by egefeyzioglu** [comment]
Could you paste the full output please? I don't get the same error when compiling. Please also make sure that you have the Nano 33 IoT selected as the board you're compiling for

**Comment by Dan-Rdd** [comment]
> Could you paste the full output please? I don't get the same error when compiling. Please also make sure that you have the Nano 33 IoT selected as the board you're compiling for

My apologies I have no idea why I put this comment in your repo I had that many tabs open my mistake this was meant for another project 0_0

**Comment by egefeyzioglu** [comment]
lmao no worries
